insert into jobs (title, description, reports_to, job_ref, status) values
('Popcorn Quality Control Specialist', 'Taste-test popcorn batches for structural crunch and emotional support value.', 'Head of Snack Logistics', 'JOB-0001', 'AVAILABLE'),
('Trapeze Calendar Coordinator', 'Schedule aerial stunts around weather, moon phases, and mild superstition.', 'Chief Acrobatical Officer', 'JOB-0002', 'AVAILABLE'),
('Lion Whisper Documentation Officer', 'Record roars as compliant meeting minutes.', 'Director of Cat Relations', 'JOB-0003', 'AVAILABLE'),
('Confetti Forecast Analyst', 'Predict confetti drift using advanced fan choreography.', 'Operations Ringmaster', 'JOB-0004', 'AVAILABLE'),
('Unicycle Stability Auditor', 'Certify one-wheel readiness during peak panic.', 'Safety Marshal of Wheels', 'JOB-0005', 'AVAILABLE'),
('Juggling KPI Strategist', 'Translate dropped objects into actionable performance metrics.', 'Chief Performance Optimist', 'JOB-0006', 'AVAILABLE'),
('Mime Liaison Associate', 'Facilitate cross-functional silence between departments.', 'Head of Quiet Affairs', 'JOB-0007', 'AVAILABLE'),
('Tent Pole Compliance Inspector', 'Ensure poles remain upright and emotionally resilient.', 'Infrastructure Ring Lead', 'JOB-0008', 'AVAILABLE'),
('Accordion Morale Director', 'Deploy morale boosts in polka-critical moments.', 'VP of Audience Feelings', 'JOB-0009', 'AVAILABLE'),
('Fire Hoop Procurement Lead', 'Source hoops with optimal flame-to-fear ratios.', 'Pyro Procurement Manager', 'JOB-0010', 'AVAILABLE'),
('Elephant Parade Route Planner', 'Map parade routes avoiding puddles and existential dread.', 'Director of Large Logistics', 'JOB-0011', 'AVAILABLE'),
('Clown Shoe Inventory Architect', 'Design a scalable system for oversized footwear.', 'Footwear Program Owner', 'JOB-0012', 'AVAILABLE'),
('Drumroll Timing Specialist', 'Deliver dramatic drumrolls at legally dramatic intervals.', 'Soundstage Ring Captain', 'JOB-0013', 'AVAILABLE'),
('Cannonball Launch Readiness Analyst', 'Verify launch prep checklists and bravery levels.', 'Aerial Systems Manager', 'JOB-0014', 'AVAILABLE'),
('Audience Gasps Curator', 'Engineer synchronized audience astonishment.', 'Chief Wonder Officer', 'JOB-0015', 'AVAILABLE'),
('Cotton Candy Load Balancer', 'Balance sugar distribution across multiple snack nodes.', 'Snack Infrastructure Lead', 'JOB-0016', 'AVAILABLE'),
('Mascot Diplomacy Envoy', 'Resolve mascot disagreements through interpretive dance.', 'Culture and Mascot Affairs', 'JOB-0017', 'AVAILABLE'),
('Spotlight Beam Tuner', 'Tune spotlight warmth for maximum protagonist energy.', 'Visual Spectacle Manager', 'JOB-0018', 'AVAILABLE'),
('Ticket Stub Archivist', 'Preserve stubs for future legends and audits.', 'Historical Compliance Director', 'JOB-0019', 'AVAILABLE'),
('Backstage Whisper Router', 'Route rumors to approved gossip channels.', 'Information Ring Controller', 'JOB-0020', 'AVAILABLE'),
('Tightrope Wind Consultant', 'Translate wind mood into rope strategy.', 'High Wire Program Lead', 'JOB-0021', 'AVAILABLE'),
('Glitter Spill Incident Commander', 'Lead containment for level-4 sparkle events.', 'Emergency Sparkle Response', 'JOB-0022', 'AVAILABLE'),
('Balloon Animal Operations Lead', 'Scale balloon outcomes with minimal squeak debt.', 'Inflatable Systems Chief', 'JOB-0023', 'AVAILABLE'),
('Applause Amplification Intern', 'Encourage clapping via ethical hand gestures.', 'Audience Engagement Manager', 'JOB-0024', 'AVAILABLE'),
('Peanut Logistics Navigator', 'Coordinate peanut flow for elephants and humans.', 'Nutritional Distribution Lead', 'JOB-0025', 'AVAILABLE'),
('Top Hat Security Analyst', 'Protect executive hats from mysterious disappearances.', 'Apparel Risk Officer', 'JOB-0026', 'AVAILABLE'),
('Stilt Height Compliance Officer', 'Enforce safe and stylish altitude standards.', 'Mobility Governance Chief', 'JOB-0027', 'AVAILABLE'),
('Ringmaster Voice Backup', 'Maintain backup announcements in case of dramatic coughs.', 'Chief Ring Communications', 'JOB-0028', 'AVAILABLE'),
('Confession Booth Queue Manager', 'Organize performer confessions by severity and sparkle.', 'People Ops Ringmaster', 'JOB-0029', 'AVAILABLE'),
('Emergency Kazoo Responder', 'Deploy kazoos to stabilize morale during outages.', 'Director of Audio Escalation', 'JOB-0030', 'AVAILABLE')
on conflict (job_ref) do nothing;
