[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[redirects]]
  from = "https://compendium-circus-hr.netlify.app/*"
  to = "https://www.thecompendiumpodcast.com/:splat"
  status = 301
  force = true

[dev]
  command = "npm run dev"
  framework = "next"
  targetPort = 3000
  port = 3000
